# Generated by Django 5.2.7 on 2025-11-28 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recetacreada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
