# Generated by Django 5.2.7 on 2026-08-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Perfil', '0003_alter_recetacreada_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='recetacreada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
